---
title: "Reproductive success of *Penstemon digitalis* increases with floral scent emission"
---

# Introduction

Floral scent is often thought to be an important part of floral phenotypes, but is rarely studied (TODO: cite). Our hypothesis is that higher floral scent emission results in higher reproductive success. This hypothesis is formed by the assumption that floral scent can help guide pollinators to the flowers, thus increasing the likelihood that offspring are successfully produced. To test this hypothesis, we analyze data collected in a garden study on a variety of phenotypic variables of *Penstemon digitalis*. Specifically, we analyze the effect of floral scent emission on a fitness variable computed by the data collectors. We include the population of origin from which a given individual came and account for the effect of experimental block.

# Methods

The data used contain a variety of phenotypic data for *P. digitalis* individuals. Each data point represents one plant. The floral scent emission was measured per plant in $ng/L/h$, while fitness was computed on fruit number and plant weight. Both floral scent emission and fitness were natural log-transformed to remove right skew in the data, shown in the model description below. Furthermore, each plant was sourced from one of three populations in the north-eastern USA, abbreviated NR, WF, and TH. Plants were arranged in a randomized complete block design, where 35 blocks each contained one plant from each of the three populations. To determine the effect of floral scent emission on fitness for individuals from each of the three source populations while accounting for the random effect of experimental block, the following generalized linear mixed model with random intercepts was fitted to the data, shown here in R syntax.

```         
log(fitness) ~ log(floral scent emission) + population + (1|block)
```

# Results

The whole model (both fixed and random effects) fitted to the data explained 26.0% of the variance in fitness across the dataset (pseudo $r^2 = 0.260$). 18.6% of the variance in fitness was explained by the experimental block (Table 1). Fitness was predicted to increased by 0.155% for each 1% increase in total scent emission ($elasticity = 0.155 \pm 0.051 \: (ng/L/h)^{-1}$, Table 2, Figure 1). At any given total scent emission, population WF had the highest predicted fitness, followed by population NR and TH, in descending order (Table 2, Figure 1). On the data scale, this meant that at a floral scent emission of $1.72 \: ng/L/h$ (the bounds of the first quartile), the predicted fitness was 68.5, 70.6, and 73.5 for populations TH, NR, and WF respectively. At a floral scent emission of $7.80 \: ng/L/h$ (the bounds of the third quartile), the predicted fitness was 86.7, 89.2, and 92.9 for populations TH, NR, and WF respectively. In other words, an increase in fitness of 18.1, 18.7, and 19.4 was predicted by the model across the interquartile range of total floral scent.

TODO: check on quartile/quantile wording TODO: Table 1, random effects TODO: Table 2, model parameter estimates

# Conclusions

The analysis presented in this report supports the hypothesis that increased floral scent emission increases fitness of *P. digitalis*. The increase was small but noticable at 0.15% increase in fitness per 1% increase in total scent emission. We found that the populations were relatively similar in how total scent emission affected fitness, but that fitness was generally the fighest for WF and the lowest for TH. We also found that a fair share of variance was represented by the experimental blocks, suggesting that the design captured the variance within groups to a large extent. In conclusion, total scent emission had a small but noticable effect on the fitness of plants, and populations were generally quite similar in regards to this relationship.

# Appendix

The repository for this project can be found at [github.com/otodreas/BIOS15_Exam/](https://github.com/otodreas/BIOS15_Exam/)

The script, data, and the report itself can be found in the GitHub repo at the following locations

```         
root/
└── Report/
    ├── Scripts/
    │   └── Analysis.R
    ├── Data/
    │   └── penstemon_copy.txt
    └── Todreas_BIOS15_Exam.pdf
```

Below is a copy of the script for reference

```{r}
#| file: Scripts/Analysis.R
#| eval: false
```